"use client";

import type { Session } from "@supabase/supabase-js";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { moshomoApi } from "@/lib/api";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Membership = { company_id: string; role: "admin" | "manager" | "employee" };
type Company = { id: string; name: string; slug: string };
type Department = { id: string; company_id: string; name: string };

export default function WorkspacePage() {
  const router = useRouter(); const [session, setSession] = useState<Session>(); const [membership, setMembership] = useState<Membership>(); const [company, setCompany] = useState<Company>(); const [departments, setDepartments] = useState<Department[]>([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<string>(); const [showSetup, setShowSetup] = useState(true);
  useEffect(() => { async function load() { const supabase = getSupabaseBrowserClient(); const { data } = await supabase.auth.getSession(); if (!data.session) { router.replace("/auth"); return; } setSession(data.session); const { data: rows } = await supabase.from("company_memberships").select("company_id,role").eq("status", "active").limit(1); const active = rows?.[0] as Membership | undefined; if (active) { setMembership(active); localStorage.setItem("moshomo_company_id", active.company_id); setShowSetup(localStorage.getItem(setupStorageKey(active.company_id)) !== "true"); const [{ data: companies }, { data: departmentRows }] = await Promise.all([supabase.from("companies").select("id,name,slug").eq("id", active.company_id).limit(1), supabase.from("departments").select("id,company_id,name").eq("company_id", active.company_id).order("name")]); setCompany(companies?.[0] as Company | undefined); setDepartments((departmentRows ?? []) as Department[]); } setLoading(false); } void load(); }, [router]);
  async function createCompany(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!session) return; const form = new FormData(event.currentTarget); try { const result = await moshomoApi<{ company_id: string }>("/companies", { method: "POST", session, body: Object.fromEntries(form) }); localStorage.setItem("moshomo_company_id", result.company_id); location.reload(); } catch (error) { setNotice(error instanceof Error ? error.message : "Company creation failed."); } }
  async function createDepartment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!session || !membership) return; const element = event.currentTarget; const form = new FormData(element); try { const department = await moshomoApi<Department>(`/companies/${membership.company_id}/departments`, { method: "POST", session, companyId: membership.company_id, body: { name: form.get("name") } }); setDepartments((current) => [...current, department]); element.reset(); setNotice("Department created."); } catch (error) { setNotice(error instanceof Error ? error.message : "Department creation failed."); } }
  async function inviteEmployee(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!session || !membership) return; const element = event.currentTarget; const body = Object.fromEntries(new FormData(element)); if (!body.department_id) delete body.department_id; try { await moshomoApi(`/companies/${membership.company_id}/invitations`, { method: "POST", session, companyId: membership.company_id, body }); element.reset(); setNotice(`Invitation sent to ${body.email}.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Invitation failed."); } }
  function skipSetup() { if (!membership) return; localStorage.setItem(setupStorageKey(membership.company_id), "true"); setShowSetup(false); setNotice(undefined); }
  function continueSetup() { if (!membership) return; localStorage.removeItem(setupStorageKey(membership.company_id)); setShowSetup(true); }
  if (loading) return <main className="grid min-h-screen place-items-center bg-stone-100">Loading Moshomo...</main>; if (!session) return null;
  if (!membership) return <AppShell><section className="mx-auto max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Step 1 of 3</p><h1 className="mt-3 text-4xl font-semibold">Create your company</h1><p className="mt-3 text-stone-600">You become the founding admin and an employee at the same time.</p><form className="mt-8 grid gap-5 rounded-3xl border border-stone-200 bg-white p-7 sm:grid-cols-2" onSubmit={createCompany}><Field label="Company name" name="company_name" /><Field label="Company slug" name="company_slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /><Field label="Employee number" name="employee_number" /><Field label="Job title" name="job_title" required={false} /><Field label="First name" name="first_name" /><Field label="Last name" name="last_name" />{notice && <p className="text-sm text-rose-700 sm:col-span-2">{notice}</p>}<button className="rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white sm:col-span-2">Create company</button></form></section></AppShell>;
  if (membership.role === "employee") return <EmployeeWorkspace company={company} role={membership.role} />;
  if (membership.role === "manager") return <ManagerWorkspace company={company} role={membership.role} />;
  if (!showSetup) return <AppShell companyName={company?.name} role={membership.role}><section className="mx-auto max-w-4xl"><p className="text-sm font-semibold text-emerald-700">Workspace</p><h1 className="mt-2 text-4xl font-semibold">Welcome to {company?.name ?? "Moshomo"}</h1><p className="mt-3 text-stone-600">Your company is ready. You can add departments and invite employees whenever you are ready.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><WorkspaceCard label="Departments" value={String(departments.length)} /><WorkspaceCard label="Leave" value="Coming soon" /><WorkspaceCard label="Shifts" value="Coming soon" /></div><button className="mt-8 rounded-xl border border-stone-300 bg-white px-5 py-3 font-semibold text-stone-800" onClick={continueSetup}>Continue company setup</button></section></AppShell>;
  return <AppShell companyName={company?.name} role={membership.role}><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Company setup</p><h1 className="mt-2 text-4xl font-semibold">Build your workforce</h1><p className="mt-3 text-stone-600">Create departments, then add employees and choose their role.</p></div><button className="rounded-xl border border-stone-300 bg-white px-5 py-3 font-semibold text-stone-800" onClick={skipSetup}>Skip for now</button></div>{notice && <p className="mb-6 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">{notice}</p>}<div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-sm font-semibold text-emerald-700">Step 2</p><h2 className="mt-2 text-2xl font-semibold">Departments</h2><form className="mt-5 flex gap-3" onSubmit={createDepartment}><input className="min-w-0 flex-1 rounded-xl border border-stone-300 px-4 py-3" name="name" placeholder="e.g. Operations" required /><button className="rounded-xl bg-stone-900 px-5 py-3 font-semibold text-white">Add</button></form><div className="mt-5 flex flex-wrap gap-2">{departments.map((item) => <span className="rounded-full bg-stone-100 px-3 py-2 text-sm" key={item.id}>{item.name}</span>)}</div></section><section className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-sm font-semibold text-emerald-700">Step 3</p><h2 className="mt-2 text-2xl font-semibold">Invite an employee</h2><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={inviteEmployee}><Field label="First name" name="first_name" /><Field label="Last name" name="last_name" /><Field label="Email" name="email" type="email" /><Field label="Employee number" name="employee_number" /><Select label="Role" name="role"><option value="employee">Employee</option><option value="manager">Manager</option><option value="admin">Admin</option></Select><Select label="Department" name="department_id"><option value="">No department</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Field label="Job title" name="job_title" required={false} /><Field label="Employment type" name="employment_type" required={false} /><button className="rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white sm:col-span-2">Create employee and send invite</button></form></section></div></AppShell>;
}

function setupStorageKey(companyId: string) { return `moshomo_onboarding_dismissed:${companyId}`; }
function WorkspaceCard({ label, value }: { label: string; value: string }) { return <div className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-sm text-stone-500">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>; }
function EmployeeWorkspace({ company, role }: { company?: Company; role: Membership["role"] }) { return <AppShell companyName={company?.name} role={role}><section className="mx-auto max-w-4xl"><p className="text-sm font-semibold text-emerald-700">Employee workspace</p><h1 className="mt-2 text-4xl font-semibold">Welcome to {company?.name ?? "Moshomo"}</h1><p className="mt-3 text-stone-600">View your shifts, manage your leave, and access your employee profile.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><WorkspaceCard label="My shifts" value="Coming soon" /><WorkspaceCard label="My leave" value="Coming soon" /><WorkspaceCard label="My profile" value="Ready soon" /></div></section></AppShell>; }
function ManagerWorkspace({ company, role }: { company?: Company; role: Membership["role"] }) { return <AppShell companyName={company?.name} role={role}><section className="mx-auto max-w-4xl"><p className="text-sm font-semibold text-emerald-700">Manager workspace</p><h1 className="mt-2 text-4xl font-semibold">Manage your team</h1><p className="mt-3 text-stone-600">Review team leave, workforce coverage, and upcoming shifts.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><WorkspaceCard label="Team" value="Coming soon" /><WorkspaceCard label="Leave requests" value="Coming soon" /><WorkspaceCard label="Shift coverage" value="Coming soon" /></div></section></AppShell>; }

function Field({ label, name, type = "text", required = true, pattern }: { label: string; name: string; type?: string; required?: boolean; pattern?: string }) { return <label className="text-sm font-medium text-stone-700">{label}<input className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3" name={name} type={type} required={required} pattern={pattern} /></label>; }
function Select({ label, name, children }: { label: string; name: string; children: React.ReactNode }) { return <label className="text-sm font-medium text-stone-700">{label}<select className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3" name={name}>{children}</select></label>; }
